name: data_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - lightgbm
  - matplotlib
  - seaborn
  - statsmodels
  - scipy
  - jupyter
  - ipykernel
  - pip